### ISSUE TITLE
Add R Markdown usage in README

### ISSUE THREAD

**Issue by jrosell** [anishathalye/auriga#2]
I think it would be useful to add a section for help using your theme from R Markdown. I created this repository here using your theme https://github.com/jrosell/rmarkdown-beamer-presentation

**Comment by anishathalye** [comment]
Hmm, where should this information go? Thoughts on having it in the wiki, and then having a mention of the Wiki in the README for this repo?

That's how I've handled contributed documentation in other projects of mine, e.g. Dotbot ([README](https://github.com/anishathalye/dotbot#wiki), [wiki](https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks)).

**Comment by jrosell** [comment]
Don't you think a section inside README.md file is enough? :)

**Comment by anishathalye** [comment]
Sure, added to the README here: https://github.com/anishathalye/auriga#notes

In general, I don't add this sort of contributed stuff to the README, because it can grow unwieldy. If we receive more material like this in the future, I might factor it out into a separate page.
